name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  update_jenkins_conf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrislennon/action-aws-cli@v1.1
      - run: |
          echo Copy key from S3 bucket...
          echo ${BUCKET}
          aws s3 cp s3://$BUCKET/key.pem key.pem
          chmod 400 key.pem
          scp -i key.pem -oStrictHostKeyChecking=no jenkins_configuration.yaml ec2-user@${JENKINS_URL}:/opt/jenkins/jenkins_home/jenkins.yaml
          echo Starting update...
          curl -X POST -u ${USER}:${TOKEN} http://${JENKINS_URL}:8080/configuration-as-code/reload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          USER: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}
